In [7]:
import pandas as pd

In [8]:
train = pd.read_csv('train_clean2.csv', encoding='utf-8')

In [9]:
train

,모델명,연식,최대출력(마력),기통,최대토크(kgm),구동방식,신차가(만원),가격(만원),주행거리,연료
0,기아 더 뉴 K7 2.4 GDI 프레스티지 스페셜,2013.0,201.0,4.0,25.5,FF,3141.0,1870.0,40000,0
1,현대 YF쏘나타 2.0 Y20 LPi 프리미어,2010.0,157.0,NaN,20.0,FF,NaN,700.0,90000,1
2,현대 그랜져HG 220 디젤 프리미엄,2015.0,202.0,4.0,45.0,FF,3389.0,2990.0,30000,2
3,쌍용 뉴카이런 2.0 LV5 2WD 고급형,2008.0,151.0,4.0,33.8,FR,2499.0,420.0,160000,2
4,현대 뉴스타렉스 점보 밴 TCI 3인승 GX 윈도우밴 일반형,2004.0,103.0,NaN,24.0,FR,1445.0,450.0,160000,2
...,...,...,...,...,...,...,...,...,...,...
11735,현대 제네시스 쿠페 200 터보 P,2009.0,210.0,4.0,30.5,FR,2641.0,111111.0,110000,0
11736,어울림모터스 스피라 S 2.7,2012.0,NaN,NaN,NaN,NaN,10508.0,10500.0,5000,0
11737,제네시스 EQ900 3.3 T-GDi AWD 프레스티지,2016.0,370.0,6.0,52.0,AWD,10900.0,10000.0,230,0
11738,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,425.0,8.0,53.0,AWD,11490.0,10300.0,9000,0
11739,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,425.0,8.0,53.0,AWD,11490.0,10800.0,3000,0

In [10]:
temp = []

for i, row in train.iterrows():
    temp.append(row['모델명'].split()[0])
    
del train['모델명']
train['car_brand'] = temp

In [12]:
for i, row in train.iterrows():
    if row['car_brand'] == '어울림모터스':
        print(row)

연식             2011
최대출력(마력)        400
기통              NaN
최대토크(kgm)      35.5
구동방식             MR
신차가(만원)         NaN
가격(만원)         4600
주행거리           4000
연료                0
car_brand    어울림모터스
Name: 1591, dtype: object
연식             2011
최대출력(마력)        420
기통                6
최대토크(kgm)        50
구동방식             FR
신차가(만원)         NaN
가격(만원)         5900
주행거리          20000
연료                0
car_brand    어울림모터스
Name: 1638, dtype: object
연식             2012
최대출력(마력)        NaN
기통              NaN
최대토크(kgm)       NaN
구동방식            NaN
신차가(만원)       10508
가격(만원)         7900
주행거리           7000
연료                0
car_brand    어울림모터스
Name: 2164, dtype: object
연식             2011
최대출력(마력)        420
기통                6
최대토크(kgm)        50
구동방식             FR
신차가(만원)         NaN
가격(만원)         4000
주행거리          10000
연료                0
car_brand    어울림모터스
Name: 7356, dtype: object
연식             2010
최대출력(마력)        NaN
기통              NaN
최대토크(kgm)       NaN
구동방식            NaN
신차가(만원)        9409
가격(만원)         3800
주행거리          10000
연료                0
car_brand    어울림모터스
Name: 7497, dtype: object
연식             2011
최대출력(마력)        NaN
기통              NaN
최대토크(kgm)       NaN
구동방식            NaN
신차가(만원)       10508
가격(만원)         3890
주행거리          20000
연료                0
car_brand    어울림모터스
Name: 10748, dtype: object
연식             2011
최대출력(마력)        400
기통              NaN
최대토크(kgm)      35.5
구동방식             MR
신차가(만원)         NaN
가격(만원)         4290
주행거리           3000
연료                0
car_brand    어울림모터스
Name: 11245, dtype: object
연식             2012
최대출력(마력)        NaN
기통              NaN
최대토크(kgm)       NaN
구동방식            NaN
신차가(만원)       10508
가격(만원)        10500
주행거리           5000
연료                0
car_brand    어울림모터스
Name: 11736, dtype: object