In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('train.csv', encoding='utf-8')

In [3]:
train

,no,모델명,연월,연식,연료,주행거리,인승,최대출력(마력),기통,최대토크(kgm),구동방식,자동수동,국산/수입,신차가(만원),가격(만원)
0,0,기아 더 뉴 K7 2.4 GDI 프레스티지 스페셜,12/12(13년형),2013.0,가솔린,4만km,NaN,201.0,4.0,25.5,FF,NaN,국산,3141.0,1870.0
1,1,현대 YF쏘나타 2.0 Y20 LPi 프리미어,10/03,2010.0,LPG,9만km,NaN,157.0,NaN,20.0,FF,NaN,국산,NaN,700.0
2,2,현대 그랜져HG 220 디젤 프리미엄,14/09(15년형),2015.0,디젤,3만km,NaN,202.0,4.0,45.0,FF,NaN,국산,3389.0,2990.0
3,3,쌍용 뉴카이런 2.0 LV5 2WD 고급형,07/06(08년형),2008.0,디젤,16만km,NaN,151.0,4.0,33.8,FR,NaN,국산,2499.0,420.0
4,4,현대 뉴스타렉스 점보 밴 TCI 3인승 GX 윈도우밴 일반형,04/03,2004.0,디젤,16만km,3.0,103.0,NaN,24.0,FR,수동,국산,1445.0,450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11764,11764,현대 제네시스 쿠페 200 터보 P,09/07,2009.0,가솔린,11만km,NaN,210.0,4.0,30.5,FR,NaN,국산,2641.0,111111.0
11765,11765,어울림모터스 스피라 S 2.7,12/06,2012.0,가솔린,5천km,NaN,NaN,NaN,NaN,NaN,수동,국산,10508.0,10500.0
11766,11766,제네시스 EQ900 3.3 T-GDi AWD 프레스티지,16/05,2016.0,가솔린,230km,NaN,370.0,6.0,52.0,AWD,NaN,국산,10900.0,10000.0
11767,11767,제네시스 EQ900 5.0 GDi AWD 프레스티지,16/01,2016.0,가솔린,9천km,NaN,425.0,8.0,53.0,AWD,NaN,국산,11490.0,10300.0
11768,11768,제네시스 EQ900 5.0 GDi AWD 프레스티지,15/12(16년형),2016.0,가솔린,3천km,NaN,425.0,8.0,53.0,AWD,NaN,국산,11490.0,10800.0

In [4]:
print(len(train))
train.isnull().sum()

11769

no               0
모델명              0
연월               0
연식               0
연료               0
주행거리             0
인승           11004
최대출력(마력)      1125
기통            3071
최대토크(kgm)     1224
구동방식           961
자동수동         10456
국산/수입            0
신차가(만원)       2225
가격(만원)           0
dtype: int64

In [5]:
del train['인승']
del train['자동수동']
del train['no']
del train['연월']

In [6]:
train.isnull().sum()

모델명             0
연식              0
연료              0
주행거리            0
최대출력(마력)     1125
기통           3071
최대토크(kgm)    1224
구동방식          961
국산/수입           0
신차가(만원)      2225
가격(만원)          0
dtype: int64

In [7]:
deli = []
dist = []

for i, row in train.iterrows():
    if '만' in row['주행거리']:
        dist.append(int(row['주행거리'][:-3]) * 10000)
    elif '천' in row['주행거리']:
        dist.append(int(row['주행거리'][:-3]) * 1000)
    else:
        if row['주행거리'] == '등록':
            deli.append(i)
            continue
        dist.append(int(row['주행거리'][:-2]))
        
train.drop(deli, inplace=True)
del train['주행거리']
train.index = range(len(train))
print(len(train))

train['주행거리'] = dist

11740

In [8]:
train

,모델명,연식,연료,최대출력(마력),기통,최대토크(kgm),구동방식,국산/수입,신차가(만원),가격(만원),주행거리
0,기아 더 뉴 K7 2.4 GDI 프레스티지 스페셜,2013.0,가솔린,201.0,4.0,25.5,FF,국산,3141.0,1870.0,40000
1,현대 YF쏘나타 2.0 Y20 LPi 프리미어,2010.0,LPG,157.0,NaN,20.0,FF,국산,NaN,700.0,90000
2,현대 그랜져HG 220 디젤 프리미엄,2015.0,디젤,202.0,4.0,45.0,FF,국산,3389.0,2990.0,30000
3,쌍용 뉴카이런 2.0 LV5 2WD 고급형,2008.0,디젤,151.0,4.0,33.8,FR,국산,2499.0,420.0,160000
4,현대 뉴스타렉스 점보 밴 TCI 3인승 GX 윈도우밴 일반형,2004.0,디젤,103.0,NaN,24.0,FR,국산,1445.0,450.0,160000
...,...,...,...,...,...,...,...,...,...,...,...
11735,현대 제네시스 쿠페 200 터보 P,2009.0,가솔린,210.0,4.0,30.5,FR,국산,2641.0,111111.0,110000
11736,어울림모터스 스피라 S 2.7,2012.0,가솔린,NaN,NaN,NaN,NaN,국산,10508.0,10500.0,5000
11737,제네시스 EQ900 3.3 T-GDi AWD 프레스티지,2016.0,가솔린,370.0,6.0,52.0,AWD,국산,10900.0,10000.0,230
11738,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,가솔린,425.0,8.0,53.0,AWD,국산,11490.0,10300.0,9000
11739,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,가솔린,425.0,8.0,53.0,AWD,국산,11490.0,10800.0,3000

In [9]:
# train_clean = train.dropna()
# print(train_clean.shape[0],train_clean.shape[1])
# 결측치를 모두 제거햇더니 총 3364개의 행이 지워짐

In [10]:
# 데이터 확인 결과 train 데이터에 국산 차 밖에 없음
del train['국산/수입']

In [11]:
train

,모델명,연식,연료,최대출력(마력),기통,최대토크(kgm),구동방식,신차가(만원),가격(만원),주행거리
0,기아 더 뉴 K7 2.4 GDI 프레스티지 스페셜,2013.0,가솔린,201.0,4.0,25.5,FF,3141.0,1870.0,40000
1,현대 YF쏘나타 2.0 Y20 LPi 프리미어,2010.0,LPG,157.0,NaN,20.0,FF,NaN,700.0,90000
2,현대 그랜져HG 220 디젤 프리미엄,2015.0,디젤,202.0,4.0,45.0,FF,3389.0,2990.0,30000
3,쌍용 뉴카이런 2.0 LV5 2WD 고급형,2008.0,디젤,151.0,4.0,33.8,FR,2499.0,420.0,160000
4,현대 뉴스타렉스 점보 밴 TCI 3인승 GX 윈도우밴 일반형,2004.0,디젤,103.0,NaN,24.0,FR,1445.0,450.0,160000
...,...,...,...,...,...,...,...,...,...,...
11735,현대 제네시스 쿠페 200 터보 P,2009.0,가솔린,210.0,4.0,30.5,FR,2641.0,111111.0,110000
11736,어울림모터스 스피라 S 2.7,2012.0,가솔린,NaN,NaN,NaN,NaN,10508.0,10500.0,5000
11737,제네시스 EQ900 3.3 T-GDi AWD 프레스티지,2016.0,가솔린,370.0,6.0,52.0,AWD,10900.0,10000.0,230
11738,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,가솔린,425.0,8.0,53.0,AWD,11490.0,10300.0,9000
11739,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,가솔린,425.0,8.0,53.0,AWD,11490.0,10800.0,3000

In [16]:
dic = {}
cnt = 0

for i in train['연료'].unique():
    dic[i] = cnt
#     cnt += 1
print(dic)

{'가솔린': 0, 'LPG': 0, '디젤': 0, '가솔린/LPG겸용': 0, '전기': 0, '가솔린+전기': 0, '수소': 0, 'LPG+전기': 0, '기타': 0, '가솔린/CNG겸용': 0, 'CNG': 0}

In [19]:
# temp = []
for i, row in train.iterrows():
#     temp.append(dic[row['연료']])
    if row['연료'] == '수소':
        print("수소 삭제", i)
        train.drop(i)
        continue
    dic[row['연료']] += 1
dic

수소 삭제 384

{'가솔린': 20013,
 'LPG': 2802,
 '디젤': 11901,
 '가솔린/LPG겸용': 123,
 '전기': 72,
 '가솔린+전기': 237,
 '수소': 0,
 'LPG+전기': 42,
 '기타': 9,
 '가솔린/CNG겸용': 12,
 'CNG': 6}

In [313]:
# del train['연료']

# train['연료'] = temp

In [314]:
train.isnull().sum()

모델명             0
연식              0
최대출력(마력)     1096
기통           3042
최대토크(kgm)    1195
구동방식          932
신차가(만원)      2196
가격(만원)          0
주행거리            0
연료              0
dtype: int64

In [315]:
train_clean = train.dropna()

In [316]:
temp = []

for i, row in train_clean.iterrows():
    if row['구동방식'] == 'FF':
        temp.append(0)
    elif row['구동방식'] == 'FR':
        temp.append(1)
    elif row['구동방식'] == '4WD':
        temp.append(2)
    elif row['구동방식'] == 'AWD':
        temp.append(3)

del train_clean['구동방식']
train_clean['구동방식'] = temp

C:\Users\leegi\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [317]:
train_clean

,모델명,연식,최대출력(마력),기통,최대토크(kgm),신차가(만원),가격(만원),주행거리,연료,구동방식
0,기아 더 뉴 K7 2.4 GDI 프레스티지 스페셜,2013.0,201.0,4.0,25.5,3141.0,1870.0,40000,0,0
2,현대 그랜져HG 220 디젤 프리미엄,2015.0,202.0,4.0,45.0,3389.0,2990.0,30000,2,0
3,쌍용 뉴카이런 2.0 LV5 2WD 고급형,2008.0,151.0,4.0,33.8,2499.0,420.0,160000,2,1
6,기아 오피러스 프리미엄 GH270 스페셜 럭셔리,2011.0,195.0,6.0,25.6,3927.0,1390.0,50000,0,0
7,기아 K7 VG350 노블레스 프리미엄,2010.0,290.0,6.0,34.5,4130.0,1530.0,100000,0,0
...,...,...,...,...,...,...,...,...,...,...
11734,제네시스 G90 5.0 GDi AWD 프레스티지,2019.0,425.0,8.0,53.0,11878.0,11200.0,2000,0,3
11735,현대 제네시스 쿠페 200 터보 P,2009.0,210.0,4.0,30.5,2641.0,111111.0,110000,0,1
11737,제네시스 EQ900 3.3 T-GDi AWD 프레스티지,2016.0,370.0,6.0,52.0,10900.0,10000.0,230,0,3
11738,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,425.0,8.0,53.0,11490.0,10300.0,9000,0,3
11739,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,425.0,8.0,53.0,11490.0,10800.0,3000,0,3

In [318]:
train

,모델명,연식,최대출력(마력),기통,최대토크(kgm),구동방식,신차가(만원),가격(만원),주행거리,연료
0,기아 더 뉴 K7 2.4 GDI 프레스티지 스페셜,2013.0,201.0,4.0,25.5,FF,3141.0,1870.0,40000,0
1,현대 YF쏘나타 2.0 Y20 LPi 프리미어,2010.0,157.0,NaN,20.0,FF,NaN,700.0,90000,1
2,현대 그랜져HG 220 디젤 프리미엄,2015.0,202.0,4.0,45.0,FF,3389.0,2990.0,30000,2
3,쌍용 뉴카이런 2.0 LV5 2WD 고급형,2008.0,151.0,4.0,33.8,FR,2499.0,420.0,160000,2
4,현대 뉴스타렉스 점보 밴 TCI 3인승 GX 윈도우밴 일반형,2004.0,103.0,NaN,24.0,FR,1445.0,450.0,160000,2
...,...,...,...,...,...,...,...,...,...,...
11735,현대 제네시스 쿠페 200 터보 P,2009.0,210.0,4.0,30.5,FR,2641.0,111111.0,110000,0
11736,어울림모터스 스피라 S 2.7,2012.0,NaN,NaN,NaN,NaN,10508.0,10500.0,5000,0
11737,제네시스 EQ900 3.3 T-GDi AWD 프레스티지,2016.0,370.0,6.0,52.0,AWD,10900.0,10000.0,230,0
11738,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,425.0,8.0,53.0,AWD,11490.0,10300.0,9000,0
11739,제네시스 EQ900 5.0 GDi AWD 프레스티지,2016.0,425.0,8.0,53.0,AWD,11490.0,10800.0,3000,0

In [319]:
corr = train.corr(method='pearson')
corr

,연식,최대출력(마력),기통,최대토크(kgm),신차가(만원),가격(만원),주행거리,연료
연식,1.000000,0.168538,-0.100083,0.196845,0.115787,0.363966,-0.602282,0.088453
최대출력(마력),0.168538,1.000000,0.761994,0.674351,0.676385,0.411174,-0.006186,-0.198671
기통,-0.100083,0.761994,1.000000,0.446644,0.743672,0.267420,0.173517,-0.242358
최대토크(kgm),0.196845,0.674351,0.446644,1.000000,0.500271,0.416833,-0.009740,0.393923
신차가(만원),0.115787,0.676385,0.743672,0.500271,1.000000,0.403709,0.016643,-0.067056
가격(만원),0.363966,0.411174,0.267420,0.416833,0.403709,1.000000,-0.347161,0.075809
주행거리,-0.602282,-0.006186,0.173517,-0.009740,0.016643,-0.347161,1.000000,0.012797
연료,0.088453,-0.198671,-0.242358,0.393923,-0.067056,0.075809,0.012797,1.000000

In [320]:
corr = train_clean.corr(method='pearson')
corr

,연식,최대출력(마력),기통,최대토크(kgm),신차가(만원),가격(만원),주행거리,연료,구동방식
연식,1.000000,0.185389,-0.093100,0.257085,0.186429,0.413979,-0.659264,0.148860,0.087219
최대출력(마력),0.185389,1.000000,0.760709,0.742054,0.820124,0.431617,-0.012912,-0.175711,0.538342
기통,-0.093100,0.760709,1.000000,0.441568,0.739923,0.259593,0.168951,-0.260128,0.413192
최대토크(kgm),0.257085,0.742054,0.441568,1.000000,0.624842,0.409649,-0.030962,0.372730,0.472883
신차가(만원),0.186429,0.820124,0.739923,0.624842,1.000000,0.479988,-0.014601,-0.093448,0.540203
가격(만원),0.413979,0.431617,0.259593,0.409649,0.479988,1.000000,-0.351895,0.033639,0.366664
주행거리,-0.659264,-0.012912,0.168951,-0.030962,-0.014601,-0.351895,1.000000,-0.015214,-0.047708
연료,0.148860,-0.175711,-0.260128,0.372730,-0.093448,0.033639,-0.015214,1.000000,-0.046536
구동방식,0.087219,0.538342,0.413192,0.472883,0.540203,0.366664,-0.047708,-0.046536,1.000000

In [321]:
# 모든 값을 전처리 후 상관관계를 분석한 결과 연료는 설명력이 너무 떨어짐
del train_clean['연료']

In [322]:
train_clean.to_csv('train_clean.csv', index = False, encoding='utf-8')
train.to_csv('train_clean2.csv', index = False, encoding='utf-8')